# Generated by Django 5.0.6 on 2024-06-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_age', models.PositiveIntegerField()),
                ('user_city', models.CharField(max_length=100)),
                ('user_hobby', models.CharField(max_length=100)),
            ],
        ),
    ]
