# Generated by Django 5.0.6 on 2024-07-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0002_alter_users_info_user_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_profile',
            old_name='user_hobbies',
            new_name='user_hobby',
        ),
    ]
